language: node_js
node_js: v8
sudo: false

addons:
  apt:
    packages:
    - libvips-dev

env:
  - HUGO_VERSION="0.30.2"

before_install:
  - curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xzv
  - chmod +x hugo && mkdir -p $HOME/.local/bin && mv hugo $HOME/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"

script:
  - npm test
  - npm run generate-thumbs
  - npm run build
