baseURL = "https://emunova.net/"
title = "Emu Nova"

DefaultContentLanguage = "fr"
languageCode = "fr-FR"
defaultContentLanguageInSubdir = false

pluralizeListTitles = false
noTimes = true
ignoreFiles = [ "\\.git$", "node_modules" ]

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
page = ["HTML"]
